### PR TITLE
Required project and synchronization fixes

### PR DESCRIPTION
**Pull request by Hipster22**
In this thread I tried to fix the flaws of the previous fixes, which affected functions that did not affect synchronization in any way. Also some bugs of synchronization with trailer for trucks were fixed. Some other corrections have also been made.

### CODE REVIEW

**Comment by Alex94-code** [comment]
After landing the client, an error began to appear: Unable to create new security page for stack
GTA5.exe system error
How to fix this error?

**Comment by Alex94-code** [comment]
The CEF must be updated to fully work with the license. I don't have time for that yet, if someone can help me and update it, it would be appreciated.
GTANetwork does not work on the EpicGames version (temporarily).

**Comment by Alex94-code** [comment]
GTANetwork is in a very sad state, my fixes revive the non-working synchronization and remove some problems, but globally the platform has a lot of problems that the developers either worsened or added during updates. So I don't know if it makes sense to continue fixing multiplayer....

**Comment by Hipster22** [comment]
Due to GTANAdam's absence and lack of attention to the platform, there will be no further fixes in this thread. All further fixes will be made in a separate fork, which you can follow in my profile.

**Pull request closed without merging**
